from typing import Union

from fastapi import FastAPI, HTTPException

from model.Pokemon import Pokemon

app = FastAPI()

pokemones = {}

def crearPokemon(id, name, types, stats):
    pokemon=Pokemon(id, name, types, stats)
    pokemones[pokemon.id] = pokemon

def crearPokPrimeraGen():
    crearPokemon("bulbasaur", 1,  ["grass", "poison"], [ {"name": "hp","base_stat": 45},{"name":"attack","base_stat": 49},{"name": "defense","base_stat": 49},{"name": "special-attack","base_stat": 65}, {"name": "special-defense","base_stat": 65}, {"name": "speed", "base_stat": 45}], )
    crearPokemon("ivysaur", 2,  ["grass", "poison"], [ {"name": "hp","base_stat": 60},{"name":"attack","base_stat": 62},{"name": "defense","base_stat": 63},{"name": "special-attack","base_stat": 80}, {"name": "special-defense","base_stat": 80}, {"name": "speed", "base_stat": 60}], )
    crearPokemon("venusaur", 3,  ["grass", "poison"], [ {"name": "hp","base_stat": 80},{"name":"attack","base_stat": 82},{"name": "defense","base_stat": 83},{"name": "special-attack","base_stat": 100}, {"name": "special-defense","base_stat": 100}, {"name": "speed", "base_stat": 80}], )
    crearPokemon("charmander", 4,  ["fire"], [ {"name": "hp","base_stat": 39},{"name":"attack","base_stat": 52},{"name": "defense","base_stat": 43},{"name": "special-attack","base_stat": 60}, {"name": "special-defense","base_stat": 50}, {"name": "speed", "base_stat": 65}], )
    crearPokemon("charmeleon", 5,  ["fire"], [ {"name": "hp","base_stat": 45},{"name":"attack","base_stat": 64},{"name": "defense","base_stat": 58},{"name": "special-attack","base_stat": 80}, {"name": "special-defense","base_stat": 65}, {"name": "speed", "base_stat": 80}], )
    crearPokemon("charizard", 6,  ["fire"], [ {"name": "hp","base_stat": 78},{"name":"attack","base_stat": 84},{"name": "defense","base_stat": 78},{"name": "special-attack","base_stat": 109}, {"name": "special-defense","base_stat": 85}, {"name": "speed", "base_stat": 100}], )
    crearPokemon("squirtle", 7,  ["water"], [ {"name": "hp","base_stat": 44},{"name":"attack","base_stat": 48},{"name": "defense","base_stat": 65},{"name": "special-attack","base_stat": 50}, {"name": "special-defense","base_stat": 64}, {"name": "speed", "base_stat": 43}], )
    crearPokemon("wartortle", 8,  ["water"], [ {"name": "hp","base_stat": 59},{"name":"attack","base_stat": 63},{"name": "defense","base_stat": 80},{"name": "special-attack","base_stat": 65}, {"name": "special-defense","base_stat": 80}, {"name": "speed", "base_stat": 58}], )
    crearPokemon("blastoise", 9,  ["water"], [ {"name": "hp","base_stat": 79},{"name":"attack","base_stat": 83},{"name": "defense","base_stat": 100},{"name": "special-attack","base_stat": 85}, {"name": "special-defense","base_stat": 105}, {"name": "speed", "base_stat": 78}], )
    crearPokemon("caterpie", 10,  ["bug"], [ {"name": "hp","base_stat": 45},{"name":"attack","base_stat": 30},{"name": "defense","base_stat": 35},{"name": "special-attack","base_stat": 20}, {"name": "special-defense","base_stat": 20}, {"name": "speed", "base_stat": 45}], )
    crearPokemon("metapod", 11,  ["bug"], [ {"name": "hp","base_stat": 50},{"name":"attack","base_stat": 20},{"name": "defense","base_stat": 55},{"name": "special-attack","base_stat": 25}, {"name": "special-defense","base_stat": 25}, {"name": "speed", "base_stat": 30}], )
    crearPokemon("butterfree", 12,  ["bug", "flying"], [ {"name": "hp","base_stat": 60},{"name":"attack","base_stat": 45},{"name": "defense","base_stat": 50},{"name": "special-attack","base_stat": 90}, {"name": "special-defense","base_stat": 80}, {"name": "speed", "base_stat": 70}], )
    crearPokemon("weedle", 13, ["bug", "poison"], [{"name": "hp", "base_stat": 40}, {"name": "attack", "base_stat": 35}, {"name": "defense", "base_stat": 30}, {"name": "special-attack", "base_stat": 20}, {"name": "special-defense", "base_stat": 20}, {"name": "speed", "base_stat": 50}])
    crearPokemon("kakuna", 14, ["bug", "poison"], [{"name": "hp", "base_stat": 45}, {"name": "attack", "base_stat": 25}, {"name": "defense", "base_stat": 50}, {"name": "special-attack", "base_stat": 25}, {"name": "special-defense", "base_stat": 25}, {"name": "speed", "base_stat": 35}])
    crearPokemon("beedrill", 15, ["bug", "poison"], [{"name": "hp", "base_stat": 65}, {"name": "attack", "base_stat": 90}, {"name": "defense", "base_stat": 40}, {"name": "special-attack", "base_stat": 45}, {"name": "special-defense", "base_stat": 80}, {"name": "speed", "base_stat": 75}])
    crearPokemon("pidgey", 16, ["normal", "flying"], [{"name": "hp", "base_stat": 40}, {"name": "attack", "base_stat": 45}, {"name": "defense", "base_stat": 40}, {"name": "special-attack", "base_stat": 35}, {"name": "special-defense", "base_stat": 35}, {"name": "speed", "base_stat": 56}])
    crearPokemon("pidgeotto", 17, ["normal", "flying"], [{"name": "hp", "base_stat": 63}, {"name": "attack", "base_stat": 60}, {"name": "defense", "base_stat": 55}, {"name": "special-attack", "base_stat": 50}, {"name": "special-defense", "base_stat": 50}, {"name": "speed", "base_stat": 71}])
    crearPokemon("pidgeot", 18, ["normal", "flying"], [{"name": "hp", "base_stat": 83}, {"name": "attack", "base_stat": 80}, {"name": "defense", "base_stat": 75}, {"name": "special-attack", "base_stat": 70}, {"name": "special-defense", "base_stat": 70}, {"name": "speed", "base_stat": 101}])
    crearPokemon("rattata", 19, ["normal"], [{"name": "hp", "base_stat": 30}, {"name": "attack", "base_stat": 56}, {"name": "defense", "base_stat": 35}, {"name": "special-attack", "base_stat": 25}, {"name": "special-defense", "base_stat": 35}, {"name": "speed", "base_stat": 72}])
    crearPokemon("raticate", 20, ["normal"], [{"name": "hp", "base_stat": 55}, {"name": "attack", "base_stat": 81}, {"name": "defense", "base_stat": 60}, {"name": "special-attack", "base_stat": 50}, {"name": "special-defense", "base_stat": 70}, {"name": "speed", "base_stat": 97}])
    crearPokemon("spearow", 21, ["normal", "flying"], [{"name": "hp", "base_stat": 40}, {"name": "attack", "base_stat": 60}, {"name": "defense", "base_stat": 30}, {"name": "special-attack", "base_stat": 31}, {"name": "special-defense", "base_stat": 31}, {"name": "speed", "base_stat": 70}])
    crearPokemon("fearow", 22, ["normal", "flying"], [{"name": "hp", "base_stat": 65}, {"name": "attack", "base_stat": 90}, {"name": "defense", "base_stat": 65}, {"name": "special-attack", "base_stat": 61}, {"name": "special-defense", "base_stat": 61}, {"name": "speed", "base_stat": 100}])
    crearPokemon("ekans", 23, ["poison"], [{"name": "hp", "base_stat": 35}, {"name": "attack", "base_stat": 60}, {"name": "defense", "base_stat": 44}, {"name": "special-attack", "base_stat": 40}, {"name": "special-defense", "base_stat": 54}, {"name": "speed", "base_stat": 55}])
    crearPokemon("arbok", 24, ["poison"], [{"name": "hp", "base_stat": 60}, {"name": "attack", "base_stat": 95}, {"name": "defense", "base_stat": 69}, {"name": "special-attack", "base_stat": 65}, {"name": "special-defense", "base_stat": 79}, {"name": "speed", "base_stat": 80}])
    crearPokemon("pikachu", 25, ["electric"], [{"name": "hp", "base_stat": 35}, {"name": "attack", "base_stat": 55}, {"name": "defense", "base_stat": 40}, {"name": "special-attack", "base_stat": 50}, {"name": "special-defense", "base_stat": 50}, {"name": "speed", "base_stat": 90}])
    crearPokemon("raichu", 26, ["electric"], [{"name": "hp", "base_stat": 60}, {"name": "attack", "base_stat": 90}, {"name": "defense", "base_stat": 55}, {"name": "special-attack", "base_stat": 90}, {"name": "special-defense", "base_stat": 80}, {"name": "speed", "base_stat": 110}])
    crearPokemon("sandshrew", 27, ["ground"], [{"name": "hp", "base_stat": 50}, {"name": "attack", "base_stat": 75}, {"name": "defense", "base_stat": 85}, {"name": "special-attack", "base_stat": 20}, {"name": "special-defense", "base_stat": 30}, {"name": "speed", "base_stat": 40}])
    crearPokemon("sandslash", 28, ["ground"], [{"name": "hp", "base_stat": 75}, {"name": "attack", "base_stat": 100}, {"name": "defense", "base_stat": 110}, {"name": "special-attack", "base_stat": 45}, {"name": "special-defense", "base_stat": 55}, {"name": "speed", "base_stat": 65}])
    crearPokemon("nidoran-f", 29, ["poison"], [{"name": "hp", "base_stat": 55}, {"name": "attack", "base_stat": 47}, {"name": "defense", "base_stat": 52}, {"name": "special-attack", "base_stat": 40}, {"name": "special-defense", "base_stat": 40}, {"name": "speed", "base_stat": 41}])
    crearPokemon("nidorina", 30, ["poison"], [{"name": "hp", "base_stat": 70}, {"name": "attack", "base_stat": 62}, {"name": "defense", "base_stat": 67}, {"name": "special-attack", "base_stat": 55}, {"name": "special-defense", "base_stat": 55}, {"name": "speed", "base_stat": 56}])
    crearPokemon("nidoqueen", 31, ["poison", "ground"], [{"name": "hp", "base_stat": 90}, {"name": "attack", "base_stat": 92}, {"name": "defense", "base_stat": 87}, {"name": "special-attack", "base_stat": 75}, {"name": "special-defense", "base_stat": 85}, {"name": "speed", "base_stat": 76}])
    crearPokemon("nidoran-m", 32, ["poison"], [{"name": "hp", "base_stat": 46}, {"name": "attack", "base_stat": 57}, {"name": "defense", "base_stat": 40}, {"name": "special-attack", "base_stat": 40}, {"name": "special-defense", "base_stat": 40}, {"name": "speed", "base_stat": 50}])
    crearPokemon("nidorino", 33, ["poison"], [{"name": "hp", "base_stat": 61}, {"name": "attack", "base_stat": 72}, {"name": "defense", "base_stat": 57}, {"name": "special-attack", "base_stat": 55}, {"name": "special-defense", "base_stat": 55}, {"name": "speed", "base_stat": 65}])
    crearPokemon("nidoking", 34, ["poison", "ground"], [{"name": "hp", "base_stat": 81}, {"name": "attack", "base_stat": 102}, {"name": "defense", "base_stat": 77}, {"name": "special-attack", "base_stat": 85}, {"name": "special-defense", "base_stat": 75}, {"name": "speed", "base_stat": 85}])
    crearPokemon("clefairy", 35, ["fairy"], [{"name": "hp", "base_stat": 70}, {"name": "attack", "base_stat": 45}, {"name": "defense", "base_stat": 48}, {"name": "special-attack", "base_stat": 60}, {"name": "special-defense", "base_stat": 65}, {"name": "speed", "base_stat": 35}])
    crearPokemon("clefable", 36, ["fairy"], [{"name": "hp", "base_stat": 95}, {"name": "attack", "base_stat": 70}, {"name": "defense", "base_stat": 73}, {"name": "special-attack", "base_stat": 95}, {"name": "special-defense", "base_stat": 90}, {"name": "speed", "base_stat": 60}])
    crearPokemon("vulpix", 37, ["fire"], [{"name": "hp", "base_stat": 38}, {"name": "attack", "base_stat": 41}, {"name": "defense", "base_stat": 40}, {"name": "special-attack", "base_stat": 50}, {"name": "special-defense", "base_stat": 65}, {"name": "speed", "base_stat": 65}])
    crearPokemon("ninetales", 38, ["fire"], [{"name": "hp", "base_stat": 73}, {"name": "attack", "base_stat": 76}, {"name": "defense", "base_stat": 75}, {"name": "special-attack", "base_stat": 81}, {"name": "special-defense", "base_stat": 100}, {"name": "speed", "base_stat": 100}])
    crearPokemon("jigglypuff", 39, ["normal", "fairy"], [{"name": "hp", "base_stat": 115}, {"name": "attack", "base_stat": 45}, {"name": "defense", "base_stat": 20}, {"name": "special-attack", "base_stat": 45}, {"name": "special-defense", "base_stat": 25}, {"name": "speed", "base_stat": 20}])
    crearPokemon("wigglytuff", 40, ["normal", "fairy"], [{"name": "hp", "base_stat": 140}, {"name": "attack", "base_stat": 70}, {"name": "defense", "base_stat": 45}, {"name": "special-attack", "base_stat": 85}, {"name": "special-defense", "base_stat": 50}, {"name": "speed", "base_stat": 45}])
    crearPokemon("zubat", 41, ["poison", "flying"], [{"name": "hp", "base_stat": 40}, {"name": "attack", "base_stat": 45}, {"name": "defense", "base_stat": 35}, {"name": "special-attack", "base_stat": 30}, {"name": "special-defense", "base_stat": 40}, {"name": "speed", "base_stat": 55}])
    crearPokemon("golbat", 42, ["poison", "flying"], [{"name": "hp", "base_stat": 75}, {"name": "attack", "base_stat": 80}, {"name": "defense", "base_stat": 70}, {"name": "special-attack", "base_stat": 65}, {"name": "special-defense", "base_stat": 75}, {"name": "speed", "base_stat": 90}])
    crearPokemon("oddish", 43, ["grass", "poison"], [{"name": "hp", "base_stat": 45}, {"name": "attack", "base_stat": 50}, {"name": "defense", "base_stat": 55}, {"name": "special-attack", "base_stat": 75}, {"name": "special-defense", "base_stat": 65}, {"name": "speed", "base_stat": 30}])
    crearPokemon("gloom", 44, ["grass", "poison"], [{"name": "hp", "base_stat": 60}, {"name": "attack", "base_stat": 65}, {"name": "defense", "base_stat": 70}, {"name": "special-attack", "base_stat": 85}, {"name": "special-defense", "base_stat": 75}, {"name": "speed", "base_stat": 40}])
    crearPokemon("vileplume", 45, ["grass", "poison"], [{"name": "hp", "base_stat": 75}, {"name": "attack", "base_stat": 80}, {"name": "defense", "base_stat": 85}, {"name": "special-attack", "base_stat": 110}, {"name": "special-defense", "base_stat": 90}, {"name": "speed", "base_stat": 50}])
    crearPokemon("paras", 46, ["bug", "grass"], [{"name": "hp", "base_stat": 35}, {"name": "attack", "base_stat": 70}, {"name": "defense", "base_stat": 55}, {"name": "special-attack", "base_stat": 45}, {"name": "special-defense", "base_stat": 55}, {"name": "speed", "base_stat": 25}])
    crearPokemon("parasect", 47, ["bug", "grass"], [{"name": "hp", "base_stat": 60}, {"name": "attack", "base_stat": 95}, {"name": "defense", "base_stat": 80}, {"name": "special-attack", "base_stat": 60}, {"name": "special-defense", "base_stat": 80}, {"name": "speed", "base_stat": 30}])
    crearPokemon("venonat", 48, ["bug", "poison"], [{"name": "hp", "base_stat": 60}, {"name": "attack", "base_stat": 55}, {"name": "defense", "base_stat": 50}, {"name": "special-attack", "base_stat": 40}, {"name": "special-defense", "base_stat": 55}, {"name": "speed", "base_stat": 45}])
    crearPokemon("venomoth", 49, ["bug", "poison"], [{"name": "hp", "base_stat": 70}, {"name": "attack", "base_stat": 65}, {"name": "defense", "base_stat": 60}, {"name": "special-attack", "base_stat": 90}, {"name": "special-defense", "base_stat": 75}, {"name": "speed", "base_stat": 90}])
    crearPokemon("diglett", 50, ["ground"], [{"name": "hp", "base_stat": 10}, {"name": "attack", "base_stat": 55}, {"name": "defense", "base_stat": 25}, {"name": "special-attack", "base_stat": 35}, {"name": "special-defense", "base_stat": 45}, {"name": "speed", "base_stat": 95}])
    crearPokemon("dugtrio", 51, ["ground"], [{"name": "hp", "base_stat": 35}, {"name": "attack", "base_stat": 80}, {"name": "defense", "base_stat": 50}, {"name": "special-attack", "base_stat": 50}, {"name": "special-defense", "base_stat": 70}, {"name": "speed", "base_stat": 120}])
    crearPokemon("meowth", 52, ["normal"], [{"name": "hp", "base_stat": 40}, {"name": "attack", "base_stat": 45}, {"name": "defense", "base_stat": 35}, {"name": "special-attack", "base_stat": 40}, {"name": "special-defense", "base_stat": 40}, {"name": "speed", "base_stat": 90}])
    crearPokemon("persian", 53, ["normal"], [{"name": "hp", "base_stat": 65}, {"name": "attack", "base_stat": 70}, {"name": "defense", "base_stat": 60}, {"name": "special-attack", "base_stat": 65}, {"name": "special-defense", "base_stat": 65}, {"name": "speed", "base_stat": 115}])
    crearPokemon("psyduck", 54, ["water"], [{"name": "hp", "base_stat": 50}, {"name": "attack", "base_stat": 52}, {"name": "defense", "base_stat": 48}, {"name": "special-attack", "base_stat": 65}, {"name": "special-defense", "base_stat": 50}, {"name": "speed", "base_stat": 55}])
    crearPokemon("golduck", 55, ["water"], [{"name": "hp", "base_stat": 80}, {"name": "attack", "base_stat": 82}, {"name": "defense", "base_stat": 78}, {"name": "special-attack", "base_stat": 95}, {"name": "special-defense", "base_stat": 80}, {"name": "speed", "base_stat": 85}])
    crearPokemon("mankey", 56, ["fighting"], [{"name": "hp", "base_stat": 40}, {"name": "attack", "base_stat": 80}, {"name": "defense", "base_stat": 35}, {"name": "special-attack", "base_stat": 35}, {"name": "special-defense", "base_stat": 45}, {"name": "speed", "base_stat": 70}])
    crearPokemon("primeape", 57, ["fighting"], [{"name": "hp", "base_stat": 65}, {"name": "attack", "base_stat": 105}, {"name": "defense", "base_stat": 60}, {"name": "special-attack", "base_stat": 60}, {"name": "special-defense", "base_stat": 70}, {"name": "speed", "base_stat": 95}])
    crearPokemon("growlithe", 58, ["fire"], [{"name": "hp", "base_stat": 55}, {"name": "attack", "base_stat": 70}, {"name": "defense", "base_stat": 45}, {"name": "special-attack", "base_stat": 70}, {"name": "special-defense", "base_stat": 50}, {"name": "speed", "base_stat": 60}])
    crearPokemon("arcanine", 59, ["fire"], [{"name": "hp", "base_stat": 90}, {"name": "attack", "base_stat": 110}, {"name": "defense", "base_stat": 80}, {"name": "special-attack", "base_stat": 100}, {"name": "special-defense", "base_stat": 80}, {"name": "speed", "base_stat": 95}])
    crearPokemon("poliwag", 60, ["water"], [{"name": "hp", "base_stat": 40}, {"name": "attack", "base_stat": 50}, {"name": "defense", "base_stat": 40}, {"name": "special-attack", "base_stat": 40}, {"name": "special-defense", "base_stat": 40}, {"name": "speed", "base_stat": 90}])
    crearPokemon("poliwhirl", 61, ["water"], [{"name": "hp", "base_stat": 65}, {"name": "attack", "base_stat": 65}, {"name": "defense", "base_stat": 65}, {"name": "special-attack", "base_stat": 50}, {"name": "special-defense", "base_stat": 50}, {"name": "speed", "base_stat": 90}])
    crearPokemon("poliwrath", 62, ["water", "fighting"], [{"name": "hp", "base_stat": 90}, {"name": "attack", "base_stat": 95}, {"name": "defense", "base_stat": 95}, {"name": "special-attack", "base_stat": 70}, {"name": "special-defense", "base_stat": 90}, {"name": "speed", "base_stat": 70}])
    crearPokemon("abra", 63, ["psychic"], [{"name": "hp", "base_stat": 25}, {"name": "attack", "base_stat": 20}, {"name": "defense", "base_stat": 15}, {"name": "special-attack", "base_stat": 105}, {"name": "special-defense", "base_stat": 55}, {"name": "speed", "base_stat": 90}])
    crearPokemon("kadabra", 64, ["psychic"], [{"name": "hp", "base_stat": 40}, {"name": "attack", "base_stat": 35}, {"name": "defense", "base_stat": 30}, {"name": "special-attack", "base_stat": 120}, {"name": "special-defense", "base_stat": 70}, {"name": "speed", "base_stat": 105}])
    crearPokemon("alakazam", 65, ["psychic"], [{"name": "hp", "base_stat": 55}, {"name": "attack", "base_stat": 50}, {"name": "defense", "base_stat": 45}, {"name": "special-attack", "base_stat": 135}, {"name": "special-defense", "base_stat": 95}, {"name": "speed", "base_stat": 120}])
    crearPokemon("machop", 66, ["fighting"], [{"name": "hp", "base_stat": 70}, {"name": "attack", "base_stat": 80}, {"name": "defense", "base_stat": 50}, {"name": "special-attack", "base_stat": 35}, {"name": "special-defense", "base_stat": 35}, {"name": "speed", "base_stat": 35}])
    crearPokemon("machoke", 67, ["fighting"], [{"name": "hp", "base_stat": 80}, {"name": "attack", "base_stat": 100}, {"name": "defense", "base_stat": 70}, {"name": "special-attack", "base_stat": 50}, {"name": "special-defense", "base_stat": 60}, {"name": "speed", "base_stat": 45}])
    crearPokemon("machamp", 68, ["fighting"], [{"name": "hp", "base_stat": 90}, {"name": "attack", "base_stat": 130}, {"name": "defense", "base_stat": 80}, {"name": "special-attack", "base_stat": 65}, {"name": "special-defense", "base_stat": 85}, {"name": "speed", "base_stat": 55}])
    crearPokemon("bellsprout", 69, ["grass", "poison"], [{"name": "hp", "base_stat": 50}, {"name": "attack", "base_stat": 75}, {"name": "defense", "base_stat": 35}, {"name": "special-attack", "base_stat": 70}, {"name": "special-defense", "base_stat": 30}, {"name": "speed", "base_stat": 40}])
    crearPokemon("weepinbell", 70, ["grass", "poison"], [{"name": "hp", "base_stat": 65}, {"name": "attack", "base_stat": 90}, {"name": "defense", "base_stat": 50}, {"name": "special-attack", "base_stat": 85}, {"name": "special-defense", "base_stat": 45}, {"name": "speed", "base_stat": 55}])
    crearPokemon("victreebel", 71, ["grass", "poison"], [{"name": "hp", "base_stat": 80}, {"name": "attack", "base_stat": 105}, {"name": "defense", "base_stat": 65}, {"name": "special-attack", "base_stat": 100}, {"name": "special-defense", "base_stat": 70}, {"name": "speed", "base_stat": 70}])
    crearPokemon("tentacool", 72, ["water", "poison"], [{"name": "hp", "base_stat": 40}, {"name": "attack", "base_stat": 40}, {"name": "defense", "base_stat": 35}, {"name": "special-attack", "base_stat": 50}, {"name": "special-defense", "base_stat": 100}, {"name": "speed", "base_stat": 70}])
    crearPokemon("tentacruel", 73, ["water", "poison"], [{"name": "hp", "base_stat": 80}, {"name": "attack", "base_stat": 70}, {"name": "defense", "base_stat": 65}, {"name": "special-attack", "base_stat": 80}, {"name": "special-defense", "base_stat": 120}, {"name": "speed", "base_stat": 100}])
    crearPokemon("geodude", 74, ["rock", "ground"], [{"name": "hp", "base_stat": 40}, {"name": "attack", "base_stat": 80}, {"name": "defense", "base_stat": 100}, {"name": "special-attack", "base_stat": 30}, {"name": "special-defense", "base_stat": 30}, {"name": "speed", "base_stat": 20}])
    crearPokemon("graveler", 75, ["rock", "ground"], [{"name": "hp", "base_stat": 55}, {"name": "attack", "base_stat": 95}, {"name": "defense", "base_stat": 115}, {"name": "special-attack", "base_stat": 45}, {"name": "special-defense", "base_stat": 45}, {"name": "speed", "base_stat": 35}])
    crearPokemon("golem", 76, ["rock", "ground"], [{"name": "hp", "base_stat": 80}, {"name": "attack", "base_stat": 120}, {"name": "defense", "base_stat": 130}, {"name": "special-attack", "base_stat": 55}, {"name": "special-defense", "base_stat": 65}, {"name": "speed", "base_stat": 45}])
    crearPokemon("ponyta", 77, ["fire"], [{"name": "hp", "base_stat": 50}, {"name": "attack", "base_stat": 85}, {"name": "defense", "base_stat": 55}, {"name": "special-attack", "base_stat": 65}, {"name": "special-defense", "base_stat": 65}, {"name": "speed", "base_stat": 90}])
    crearPokemon("rapidash", 78, ["fire"], [{"name": "hp", "base_stat": 65}, {"name": "attack", "base_stat": 100}, {"name": "defense", "base_stat": 70}, {"name": "special-attack", "base_stat": 80}, {"name": "special-defense", "base_stat": 80}, {"name": "speed", "base_stat": 105}])
    crearPokemon("slowpoke", 79, ["water", "psychic"], [{"name": "hp", "base_stat": 90}, {"name": "attack", "base_stat": 65}, {"name": "defense", "base_stat": 65}, {"name": "special-attack", "base_stat": 40}, {"name": "special-defense", "base_stat": 40}, {"name": "speed", "base_stat": 15}])
    crearPokemon("slowbro", 80, ["water", "psychic"], [{"name": "hp", "base_stat": 95}, {"name": "attack", "base_stat": 75}, {"name": "defense", "base_stat": 110}, {"name": "special-attack", "base_stat": 100}, {"name": "special-defense", "base_stat": 80}, {"name": "speed", "base_stat": 30}])
    crearPokemon("magnemite", 81, ["electric", "steel"], [{"name": "hp", "base_stat": 25}, {"name": "attack", "base_stat": 35}, {"name": "defense", "base_stat": 70}, {"name": "special-attack", "base_stat": 95}, {"name": "special-defense", "base_stat": 55}, {"name": "speed", "base_stat": 45}])
    crearPokemon("magneton", 82, ["electric", "steel"], [{"name": "hp", "base_stat": 50}, {"name": "attack", "base_stat": 60}, {"name": "defense", "base_stat": 95}, {"name": "special-attack", "base_stat": 120}, {"name": "special-defense", "base_stat": 70}, {"name": "speed", "base_stat": 70}])
    crearPokemon("farfetchd", 83, ["normal", "flying"], [{"name": "hp", "base_stat": 52}, {"name": "attack", "base_stat": 90}, {"name": "defense", "base_stat": 55}, {"name": "special-attack", "base_stat": 58}, {"name": "special-defense", "base_stat": 62}, {"name": "speed", "base_stat": 60}])
    crearPokemon("doduo", 84, ["normal", "flying"], [{"name": "hp", "base_stat": 35}, {"name": "attack", "base_stat": 85}, {"name": "defense", "base_stat": 45}, {"name": "special-attack", "base_stat": 35}, {"name": "special-defense", "base_stat": 35}, {"name": "speed", "base_stat": 75}])
    crearPokemon("dodrio", 85, ["normal", "flying"], [{"name": "hp", "base_stat": 60}, {"name": "attack", "base_stat": 110}, {"name": "defense", "base_stat": 70}, {"name": "special-attack", "base_stat": 60}, {"name": "special-defense", "base_stat": 60}, {"name": "speed", "base_stat": 110}])
    crearPokemon("seel", 86, ["water"], [{"name": "hp", "base_stat": 65}, {"name": "attack", "base_stat": 45}, {"name": "defense", "base_stat": 55}, {"name": "special-attack", "base_stat": 45}, {"name": "special-defense", "base_stat": 70}, {"name": "speed", "base_stat": 45}])
    crearPokemon("dewgong", 87, ["water", "ice"], [{"name": "hp", "base_stat": 90}, {"name": "attack", "base_stat": 70}, {"name": "defense", "base_stat": 80}, {"name": "special-attack", "base_stat": 70}, {"name": "special-defense", "base_stat": 95}, {"name": "speed", "base_stat": 70}])
    crearPokemon("grimer", 88, ["poison"], [{"name": "hp", "base_stat": 80}, {"name": "attack", "base_stat": 80}, {"name": "defense", "base_stat": 50}, {"name": "special-attack", "base_stat": 40}, {"name": "special-defense", "base_stat": 50}, {"name": "speed", "base_stat": 25}])
    crearPokemon("muk", 89, ["poison"], [{"name": "hp", "base_stat": 105}, {"name": "attack", "base_stat": 105}, {"name": "defense", "base_stat": 75}, {"name": "special-attack", "base_stat": 65}, {"name": "special-defense", "base_stat": 100}, {"name": "speed", "base_stat": 50}])
    crearPokemon("shellder", 90, ["water"], [{"name": "hp", "base_stat": 30}, {"name": "attack", "base_stat": 65}, {"name": "defense", "base_stat": 100}, {"name": "special-attack", "base_stat": 45}, {"name": "special-defense", "base_stat": 25}, {"name": "speed", "base_stat": 40}])
    crearPokemon("cloyster", 91, ["water", "ice"], [{"name": "hp", "base_stat": 50}, {"name": "attack", "base_stat": 95}, {"name": "defense", "base_stat": 180}, {"name": "special-attack", "base_stat": 85}, {"name": "special-defense", "base_stat": 45}, {"name": "speed", "base_stat": 70}])
    crearPokemon("gastly", 92, ["ghost", "poison"], [{"name": "hp", "base_stat": 30}, {"name": "attack", "base_stat": 35}, {"name": "defense", "base_stat": 30}, {"name": "special-attack", "base_stat": 100}, {"name": "special-defense", "base_stat": 35}, {"name": "speed", "base_stat": 80}])
    crearPokemon("haunter", 93, ["ghost", "poison"], [{"name": "hp", "base_stat": 45}, {"name": "attack", "base_stat": 50}, {"name": "defense", "base_stat": 45}, {"name": "special-attack", "base_stat": 115}, {"name": "special-defense", "base_stat": 55}, {"name": "speed", "base_stat": 95}])
    crearPokemon("gengar", 94, ["ghost", "poison"], [{"name": "hp", "base_stat": 60}, {"name": "attack", "base_stat": 65}, {"name": "defense", "base_stat": 60}, {"name": "special-attack", "base_stat": 130}, {"name": "special-defense", "base_stat": 75}, {"name": "speed", "base_stat": 110}])
    crearPokemon("onix", 95, ["rock", "ground"], [{"name": "hp", "base_stat": 35}, {"name": "attack", "base_stat": 45}, {"name": "defense", "base_stat": 160}, {"name": "special-attack", "base_stat": 30}, {"name": "special-defense", "base_stat": 45}, {"name": "speed", "base_stat": 70}])
    crearPokemon("drowzee", 96, ["psychic"], [{"name": "hp", "base_stat": 60}, {"name": "attack", "base_stat": 48}, {"name": "defense", "base_stat": 45}, {"name": "special-attack", "base_stat": 43}, {"name": "special-defense", "base_stat": 90}, {"name": "speed", "base_stat": 42}])
    crearPokemon("hypno", 97, ["psychic"], [{"name": "hp", "base_stat": 85}, {"name": "attack", "base_stat": 73}, {"name": "defense", "base_stat": 70}, {"name": "special-attack", "base_stat": 73}, {"name": "special-defense", "base_stat": 115}, {"name": "speed", "base_stat": 67}])
    crearPokemon("krabby", 98, ["water"], [{"name": "hp", "base_stat": 30}, {"name": "attack", "base_stat": 105}, {"name": "defense", "base_stat": 90}, {"name": "special-attack", "base_stat": 25}, {"name": "special-defense", "base_stat": 25}, {"name": "speed", "base_stat": 50}])
    crearPokemon("kingler", 99, ["water"], [{"name": "hp", "base_stat": 55}, {"name": "attack", "base_stat": 130}, {"name": "defense", "base_stat": 115}, {"name": "special-attack", "base_stat": 50}, {"name": "special-defense", "base_stat": 50}, {"name": "speed", "base_stat": 75}])
    crearPokemon("voltorb", 100, ["electric"], [{"name": "hp", "base_stat": 40}, {"name": "attack", "base_stat": 30}, {"name": "defense", "base_stat": 50}, {"name": "special-attack", "base_stat": 55}, {"name": "special-defense", "base_stat": 55}, {"name": "speed", "base_stat": 100}])
    crearPokemon("electrode", 101, ["electric"], [{"name": "hp", "base_stat": 60}, {"name": "attack", "base_stat": 50}, {"name": "defense", "base_stat": 70}, {"name": "special-attack", "base_stat": 80}, {"name": "special-defense", "base_stat": 80}, {"name": "speed", "base_stat": 150}])
    crearPokemon("exeggcute", 102, ["grass", "psychic"], [{"name": "hp", "base_stat": 60}, {"name": "attack", "base_stat": 40}, {"name": "defense", "base_stat": 80}, {"name": "special-attack", "base_stat": 60}, {"name": "special-defense", "base_stat": 45}, {"name": "speed", "base_stat": 40}])
    crearPokemon("exeggutor", 103, ["grass", "psychic"], [{"name": "hp", "base_stat": 95}, {"name": "attack", "base_stat": 95}, {"name": "defense", "base_stat": 85}, {"name": "special-attack", "base_stat": 125}, {"name": "special-defense", "base_stat": 65}, {"name": "speed", "base_stat": 55}])
    crearPokemon("cubone", 104, ["ground"], [{"name": "hp", "base_stat": 50}, {"name": "attack", "base_stat": 50}, {"name": "defense", "base_stat": 95}, {"name": "special-attack", "base_stat": 40}, {"name": "special-defense", "base_stat": 50}, {"name": "speed", "base_stat": 35}])
    crearPokemon("marowak", 105, ["ground"], [{"name": "hp", "base_stat": 60}, {"name": "attack", "base_stat": 80}, {"name": "defense", "base_stat": 110}, {"name": "special-attack", "base_stat": 50}, {"name": "special-defense", "base_stat": 80}, {"name": "speed", "base_stat": 45}])
    crearPokemon("hitmonlee", 106, ["fighting"], [{"name": "hp", "base_stat": 50}, {"name": "attack", "base_stat": 120}, {"name": "defense", "base_stat": 53}, {"name": "special-attack", "base_stat": 35}, {"name": "special-defense", "base_stat": 110}, {"name": "speed", "base_stat": 87}])
    crearPokemon("hitmonchan", 107, ["fighting"], [{"name": "hp", "base_stat": 50}, {"name": "attack", "base_stat": 105}, {"name": "defense", "base_stat": 79}, {"name": "special-attack", "base_stat": 35}, {"name": "special-defense", "base_stat": 110}, {"name": "speed", "base_stat": 76}])
    crearPokemon("hitmonchan", 107, ["fighting"], [{"name": "hp", "base_stat": 50}, {"name": "attack", "base_stat": 105}, {"name": "defense", "base_stat": 79}, {"name": "special-attack", "base_stat": 35}, {"name": "special-defense", "base_stat": 110}, {"name": "speed", "base_stat": 76}])
    crearPokemon("koffing", 108, ["poison"], [{"name": "hp", "base_stat": 40}, {"name": "attack", "base_stat": 65}, {"name": "defense", "base_stat": 95}, {"name": "special-attack", "base_stat": 60}, {"name": "special-defense", "base_stat": 45}, {"name": "speed", "base_stat": 35}])
    crearPokemon("weezing", 109, ["poison"], [{"name": "hp", "base_stat": 65}, {"name": "attack", "base_stat": 90}, {"name": "defense", "base_stat": 120}, {"name": "special-attack", "base_stat": 85}, {"name": "special-defense", "base_stat": 70}, {"name": "speed", "base_stat": 60}])
    crearPokemon("rhyhorn", 110, ["ground", "rock"], [{"name": "hp", "base_stat": 80}, {"name": "attack", "base_stat": 85}, {"name": "defense", "base_stat": 95}, {"name": "special-attack", "base_stat": 30}, {"name": "special-defense", "base_stat": 30}, {"name": "speed", "base_stat": 25}])
    crearPokemon("rhydon", 111, ["ground", "rock"], [{"name": "hp", "base_stat": 105}, {"name": "attack", "base_stat": 130}, {"name": "defense", "base_stat": 120}, {"name": "special-attack", "base_stat": 45}, {"name": "special-defense", "base_stat": 45}, {"name": "speed", "base_stat": 40}])
    crearPokemon("chansey", 113, ["normal"], [{"name": "hp", "base_stat": 250}, {"name": "attack", "base_stat": 5}, {"name": "defense", "base_stat": 5}, {"name": "special-attack", "base_stat": 35}, {"name": "special-defense", "base_stat": 105}, {"name": "speed", "base_stat": 50}])
    crearPokemon("tangela", 114, ["grass"], [{"name": "hp", "base_stat": 65}, {"name": "attack", "base_stat": 55}, {"name": "defense", "base_stat": 115}, {"name": "special-attack", "base_stat": 100}, {"name": "special-defense", "base_stat": 40}, {"name": "speed", "base_stat": 60}])
    crearPokemon("kangaskhan", 115, ["normal"], [{"name": "hp", "base_stat": 105}, {"name": "attack", "base_stat": 95}, {"name": "defense", "base_stat": 80}, {"name": "special-attack", "base_stat": 40}, {"name": "special-defense", "base_stat": 80}, {"name": "speed", "base_stat": 90}])
    crearPokemon("horsea", 116, ["water"], [{"name": "hp", "base_stat": 30}, {"name": "attack", "base_stat": 40}, {"name": "defense", "base_stat": 70}, {"name": "special-attack", "base_stat": 70}, {"name": "special-defense", "base_stat": 25}, {"name": "speed", "base_stat": 60}])
    crearPokemon("seadra", 117, ["water"], [{"name": "hp", "base_stat": 55}, {"name": "attack", "base_stat": 65}, {"name": "defense", "base_stat": 95}, {"name": "special-attack", "base_stat": 95}, {"name": "special-defense", "base_stat": 45}, {"name": "speed", "base_stat": 85}])
    crearPokemon("goldeen", 118, ["water"], [{"name": "hp", "base_stat": 45}, {"name": "attack", "base_stat": 67}, {"name": "defense", "base_stat": 60}, {"name": "special-attack", "base_stat": 35}, {"name": "special-defense", "base_stat": 50}, {"name": "speed", "base_stat": 63}])
    crearPokemon("seaking", 119, ["water"], [{"name": "hp", "base_stat": 80}, {"name": "attack", "base_stat": 92}, {"name": "defense", "base_stat": 65}, {"name": "special-attack", "base_stat": 65}, {"name": "special-defense", "base_stat": 80}, {"name": "speed", "base_stat": 68}])
    crearPokemon("staryu", 120, ["water"], [{"name": "hp", "base_stat": 30}, {"name": "attack", "base_stat": 45}, {"name": "defense", "base_stat": 55}, {"name": "special-attack", "base_stat": 70}, {"name": "special-defense", "base_stat": 55}, {"name": "speed", "base_stat": 85}])
    crearPokemon("starmie", 121, ["water", "psychic"], [{"name": "hp", "base_stat": 60}, {"name": "attack", "base_stat": 75}, {"name": "defense", "base_stat": 85}, {"name": "special-attack", "base_stat": 100}, {"name": "special-defense", "base_stat": 85}, {"name": "speed", "base_stat": 115}])
    crearPokemon("mr-mime", 122, ["psychic", "fairy"], [{"name": "hp", "base_stat": 40}, {"name": "attack", "base_stat": 45}, {"name": "defense", "base_stat": 65}, {"name": "special-attack", "base_stat": 100}, {"name": "special-defense", "base_stat": 120}, {"name": "speed", "base_stat": 90}])
    crearPokemon("scyther", 123, ["bug", "flying"], [{"name": "hp", "base_stat": 70}, {"name": "attack", "base_stat": 110}, {"name": "defense", "base_stat": 80}, {"name": "special-attack", "base_stat": 55}, {"name": "special-defense", "base_stat": 80}, {"name": "speed", "base_stat": 105}])
    crearPokemon("jynx", 124, ["ice", "psychic"], [{"name": "hp", "base_stat": 65}, {"name": "attack", "base_stat": 50}, {"name": "defense", "base_stat": 35}, {"name": "special-attack", "base_stat": 115}, {"name": "special-defense", "base_stat": 95}, {"name": "speed", "base_stat": 95}])
    crearPokemon("electabuzz", 125, ["electric"], [{"name": "hp", "base_stat": 65}, {"name": "attack", "base_stat": 83}, {"name": "defense", "base_stat": 57}, {"name": "special-attack", "base_stat": 95}, {"name": "special-defense", "base_stat": 85}, {"name": "speed", "base_stat": 105}])
    crearPokemon("magmar", 126, ["fire"], [{"name": "hp", "base_stat": 65}, {"name": "attack", "base_stat": 95}, {"name": "defense", "base_stat": 57}, {"name": "special-attack", "base_stat": 100}, {"name": "special-defense", "base_stat": 85}, {"name": "speed", "base_stat": 93}])
    crearPokemon("pinsir", 127, ["bug"], [{"name": "hp", "base_stat": 65}, {"name": "attack", "base_stat": 125}, {"name": "defense", "base_stat": 100}, {"name": "special-attack", "base_stat": 55}, {"name": "special-defense", "base_stat": 70}, {"name": "speed", "base_stat": 85}])
    crearPokemon("tauros", 128, ["normal"], [{"name": "hp", "base_stat": 75}, {"name": "attack", "base_stat": 100}, {"name": "defense", "base_stat": 95}, {"name": "special-attack", "base_stat": 40}, {"name": "special-defense", "base_stat": 70}, {"name": "speed", "base_stat": 110}])
    crearPokemon("magikarp", 129, ["water"], [{"name": "hp", "base_stat": 20}, {"name": "attack", "base_stat": 10}, {"name": "defense", "base_stat": 55}, {"name": "special-attack", "base_stat": 15}, {"name": "special-defense", "base_stat": 20}, {"name": "speed", "base_stat": 80}])
    crearPokemon("gyarados", 130, ["water", "flying"], [{"name": "hp", "base_stat": 95}, {"name": "attack", "base_stat": 125}, {"name": "defense", "base_stat": 79}, {"name": "special-attack", "base_stat": 60}, {"name": "special-defense", "base_stat": 100}, {"name": "speed", "base_stat": 81}])
    crearPokemon("lapras", 131, ["water", "ice"], [{"name": "hp", "base_stat": 130}, {"name": "attack", "base_stat": 85}, {"name": "defense", "base_stat": 80}, {"name": "special-attack", "base_stat": 85}, {"name": "special-defense", "base_stat": 95}, {"name": "speed", "base_stat": 60}])
    crearPokemon("ditto", 132, ["normal"], [{"name": "hp", "base_stat": 48}, {"name": "attack", "base_stat": 48}, {"name": "defense", "base_stat": 48}, {"name": "special-attack", "base_stat": 48}, {"name": "special-defense", "base_stat": 48}, {"name": "speed", "base_stat": 48}])
    crearPokemon("eevee", 133, ["normal"], [{"name": "hp", "base_stat": 55}, {"name": "attack", "base_stat": 55}, {"name": "defense", "base_stat": 50}, {"name": "special-attack", "base_stat": 45}, {"name": "special-defense", "base_stat": 65}, {"name": "speed", "base_stat": 55}])
    crearPokemon("vaporeon", 134, ["water"], [{"name": "hp", "base_stat": 130}, {"name": "attack", "base_stat": 65}, {"name": "defense", "base_stat": 60}, {"name": "special-attack", "base_stat": 110}, {"name": "special-defense", "base_stat": 95}, {"name": "speed", "base_stat": 65}])
    crearPokemon("jolteon", 135, ["electric"], [{"name": "hp", "base_stat": 65}, {"name": "attack", "base_stat": 65}, {"name": "defense", "base_stat": 60}, {"name": "special-attack", "base_stat": 110}, {"name": "special-defense", "base_stat": 95}, {"name": "speed", "base_stat": 130}])
    crearPokemon("flareon", 136, ["fire"], [{"name": "hp", "base_stat": 65}, {"name": "attack", "base_stat": 130}, {"name": "defense", "base_stat": 60}, {"name": "special-attack", "base_stat": 95}, {"name": "special-defense", "base_stat": 110}, {"name": "speed", "base_stat": 65}])
    crearPokemon("porygon", 137, ["normal"], [{"name": "hp", "base_stat": 65}, {"name": "attack", "base_stat": 60}, {"name": "defense", "base_stat": 70}, {"name": "special-attack", "base_stat": 85}, {"name": "special-defense", "base_stat": 75}, {"name": "speed", "base_stat": 40}])
    crearPokemon("omanyte", 138, ["rock", "water"], [{"name": "hp", "base_stat": 35}, {"name": "attack", "base_stat": 40}, {"name": "defense", "base_stat": 100}, {"name": "special-attack", "base_stat": 90}, {"name": "special-defense", "base_stat": 55}, {"name": "speed", "base_stat": 35}])
    crearPokemon("omastar", 139, ["rock", "water"], [{"name": "hp", "base_stat": 70}, {"name": "attack", "base_stat": 60}, {"name": "defense", "base_stat": 125}, {"name": "special-attack", "base_stat": 115}, {"name": "special-defense", "base_stat": 70}, {"name": "speed", "base_stat": 55}])
    crearPokemon("kabuto", 140, ["rock", "water"], [{"name": "hp", "base_stat": 30}, {"name": "attack", "base_stat": 80}, {"name": "defense", "base_stat": 90}, {"name": "special-attack", "base_stat": 55}, {"name": "special-defense", "base_stat": 45}, {"name": "speed", "base_stat": 55}])
    crearPokemon("kabutops", 141, ["rock", "water"], [{"name": "hp", "base_stat": 60}, {"name": "attack", "base_stat": 115}, {"name": "defense", "base_stat": 105}, {"name": "special-attack", "base_stat": 65}, {"name": "special-defense", "base_stat": 70}, {"name": "speed", "base_stat": 80}])
    crearPokemon("aerodactyl", 142, ["rock", "flying"], [{"name": "hp", "base_stat": 80}, {"name": "attack", "base_stat": 105}, {"name": "defense", "base_stat": 65}, {"name": "special-attack", "base_stat": 60}, {"name": "special-defense", "base_stat": 75}, {"name": "speed", "base_stat": 130}])
    crearPokemon("snorlax", 143, ["normal"], [{"name": "hp", "base_stat": 160}, {"name": "attack", "base_stat": 110}, {"name": "defense", "base_stat": 65}, {"name": "special-attack", "base_stat": 65}, {"name": "special-defense", "base_stat": 110}, {"name": "speed", "base_stat": 30}])
    crearPokemon("articuno", 144, ["ice", "flying"], [{"name": "hp", "base_stat": 90}, {"name": "attack", "base_stat": 85}, {"name": "defense", "base_stat": 100}, {"name": "special-attack", "base_stat": 95}, {"name": "special-defense", "base_stat": 125}, {"name": "speed", "base_stat": 85}])
    crearPokemon("zapdos", 145, ["electric", "flying"], [{"name": "hp", "base_stat": 90}, {"name": "attack", "base_stat": 90}, {"name": "defense", "base_stat": 85}, {"name": "special-attack", "base_stat": 125}, {"name": "special-defense", "base_stat": 90}, {"name": "speed", "base_stat": 100}])
    crearPokemon("moltres", 146, ["fire", "flying"], [{"name": "hp", "base_stat": 90}, {"name": "attack", "base_stat": 100}, {"name": "defense", "base_stat": 90}, {"name": "special-attack", "base_stat": 125}, {"name": "special-defense", "base_stat": 85}, {"name": "speed", "base_stat": 90}])
    crearPokemon("dratini", 147, ["dragon"], [{"name": "hp", "base_stat": 41}, {"name": "attack", "base_stat": 64}, {"name": "defense", "base_stat": 45}, {"name": "special-attack", "base_stat": 50}, {"name": "special-defense", "base_stat": 50}, {"name": "speed", "base_stat": 50}])
    crearPokemon("dragonair", 148, ["dragon"], [{"name": "hp", "base_stat": 61}, {"name": "attack", "base_stat": 84}, {"name": "defense", "base_stat": 65}, {"name": "special-attack", "base_stat": 70}, {"name": "special-defense", "base_stat": 70}, {"name": "speed", "base_stat": 70}])
    crearPokemon("dragonite", 149, ["dragon", "flying"], [{"name": "hp", "base_stat": 91}, {"name": "attack", "base_stat": 134}, {"name": "defense", "base_stat": 95}, {"name": "special-attack", "base_stat": 100}, {"name": "special-defense", "base_stat": 100}, {"name": "speed", "base_stat": 80}])
    crearPokemon("mewtwo", 150, ["psychic"], [{"name": "hp", "base_stat": 106}, {"name": "attack", "base_stat": 110}, {"name": "defense", "base_stat": 90}, {"name": "special-attack", "base_stat": 154}, {"name": "special-defense", "base_stat": 90}, {"name": "speed", "base_stat": 130}])
    crearPokemon("mew", 151, ["psychic"], [{"name": "hp", "base_stat": 100}, {"name": "attack", "base_stat": 100}, {"name": "defense", "base_stat": 100}, {"name": "special-attack", "base_stat": 100}, {"name": "special-defense", "base_stat": 100}, {"name": "speed", "base_stat": 100}])


    
crearPokPrimeraGen()

@app.get("/")
def read_root():
    return {"Hello": "Pokapi"}

@app.get("/elrio")
def read_root():
    return {"El rio": "una mierda https://www.youtube.com/watch?v=-ApUNLzsSRc"}




@app.get("/getpokemon/{item_id}")
def read_itemread_item(item_id: int):
    try:
        text = pokemones[item_id]
    except KeyError:
        raise HTTPException(status_code=404, detail="Item not found") from KeyError

    return text

@app.get("/getpokemonbyname/{pokemon_name}")
def read_item(pokemon_name):
    try:
        text = pokemon = next((pokemon for pokemon in pokemones.values() if pokemon.name.lower() == pokemon_name.lower()), None)
        
        if pokemon is None:
            raise KeyError
        
    except KeyError:
        return {"ERROR": 404}

    return text


@app.post("/createpokemon/{name}")
def read_itemread_item(name):
    if not (name.isdigit()):
        try:
            pokeTemp = Pokemon(name)
            pokemones[name]=pokeTemp
            text = name + " created"
            return {"return": text}
        except KeyError:
            return {"ERROR: ": 404}
    else:
        text = "No valido"
    return {"return": text}